# Generated by Django 3.1.7 on 2021-03-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('visibility', models.BooleanField()),
                ('recipe_type', models.CharField(max_length=20)),
                ('prep_time', models.IntegerField()),
                ('cook_time', models.IntegerField()),
                ('cook_temp', models.IntegerField()),
                ('cook_unit', models.CharField(max_length=1)),
                ('yields', models.IntegerField()),
                ('ingredients', models.JSONField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
