# Generated by Django 3.1.7 on 2021-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yields',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
